# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def swift_pods
    
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RealmSwift'
    pod "RxRealm"

end

target 'to-do-list' do
  use_frameworks!

# inhibit_all_warnings!
    
  swift_pods  

  target 'to-do-listTests' do
    inherit! :search_paths
    # Pods for testing
    swift_pods
  end

  target 'to-do-listUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
